import { AppCategory, ApplicationInstalled } from '@ng-ios/application';

import { AppVoidComponent, AppVoidIconComponent } from '@ng-ios/app-void';
import { AppClockComponent, AppClockIconComponent } from '@ng-ios/app-clock';
import { AppSettingsComponent, AppSettingsIconComponent } from '@ng-ios/app-settings';

export const apps: ApplicationInstalled[][] = [
  [
    {
      id: 'a1',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a2',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a3',
      category: AppCategory.Other,
      label: 'Camera',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a4',
      category: AppCategory.Other,
      label: 'Test 4 4 4 4 4 4 4',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a5',
      category: AppCategory.Other,
      label: 'Test 5',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a6',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a7',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'app-clock',
      category: AppCategory.Other,
      label: 'Clock',
      icon: AppClockIconComponent,
      app: AppClockComponent,
    },
    {
      id: 'a9',
      category: AppCategory.Other,
      label: 'Test 4 4 4 4 4 4 4',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a10',
      category: AppCategory.Other,
      label: 'Test 5',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a11',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'app-settings',
      category: AppCategory.Other,
      label: 'Settings',
      icon: AppSettingsIconComponent,
      app: AppSettingsComponent,
    },
    {
      id: 'a13',
      category: AppCategory.Other,
      label: 'Camera',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a14',
      category: AppCategory.Other,
      label: 'Test 4 4 4 4 4 4 4',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a15',
      category: AppCategory.Other,
      label: 'Test 5',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a16',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a17',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a18',
      category: AppCategory.Other,
      label: 'Camera',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a19',
      category: AppCategory.Other,
      label: 'Test 4 4 4 4 4 4 4',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a20',
      category: AppCategory.Other,
      label: 'Test 5',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a21',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a22',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a23',
      category: AppCategory.Other,
      label: 'Camera',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
  ],

  [
    {
      id: 'a24',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a25',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a26',
      category: AppCategory.Other,
      label: 'Camera',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a27',
      category: AppCategory.Other,
      label: 'Test 4 4 4 4 4 4 4',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a28',
      category: AppCategory.Other,
      label: 'Test 5',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a29',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a30',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a31',
      category: AppCategory.Other,
      label: 'Camera',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a32',
      category: AppCategory.Other,
      label: 'Test 4 4 4 4 4 4 4',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a33',
      category: AppCategory.Other,
      label: 'Test 5',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a34',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a35',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
  ],

  [
    {
      id: 'a36',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
  ],

  [
    {
      id: 'a37',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
  ],

  [
    {
      id: 'a38',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
  ],
];
