import { Injectable, signal } from '@angular/core';

import { AppCategory, ApplicationInstalled } from '@ng-ios/types';
import { AppVoidComponent, AppVoidIconComponent } from '@ng-ios/app-void';
import { AppClockComponent, AppClockIconComponent } from '@ng-ios/app-clock';
import { AppSettingsComponent, AppSettingsIconComponent } from '@ng-ios/app-settings';

export const appsGrid: ApplicationInstalled[][] = [
  [
    {
      id: 'a1',
      idGrid: 'app-grid_a1',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a2',
      idGrid: 'app-grid_a2',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a3',
      idGrid: 'app-grid_a3',
      category: AppCategory.Other,
      label: 'Camera',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a4',
      idGrid: 'app-grid_a4',
      category: AppCategory.Other,
      label: 'Test 4 4 4 4 4 4 4',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a5',
      idGrid: 'app-grid_a5',
      category: AppCategory.Other,
      label: 'Test 5',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a6',
      idGrid: 'app-grid_a6',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a7',
      idGrid: 'app-grid_a7',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'app-clock',
      idGrid: 'app-grid_clock',
      category: AppCategory.Other,
      label: 'Clock',
      icon: AppClockIconComponent,
      app: AppClockComponent,
    },
    {
      id: 'a9',
      idGrid: 'app-grid_a9',
      category: AppCategory.Other,
      label: 'Test 4 4 4 4 4 4 4',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a10',
      idGrid: 'app-grid_a10',
      category: AppCategory.Other,
      label: 'Test 5',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a11',
      idGrid: 'app-grid_a11',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'app-settings',
      idGrid: 'app-grid_settings',
      category: AppCategory.Other,
      label: 'Settings',
      icon: AppSettingsIconComponent,
      app: AppSettingsComponent,
    },
    {
      id: 'a13',
      idGrid: 'app-grid_a13',
      category: AppCategory.Other,
      label: 'Camera',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a14',
      idGrid: 'app-grid_a14',
      category: AppCategory.Other,
      label: 'Test 4 4 4 4 4 4 4',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a15',
      idGrid: 'app-grid_a15',
      category: AppCategory.Other,
      label: 'Test 5',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a16',
      idGrid: 'app-grid_a16',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a17',
      idGrid: 'app-grid_a17',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a18',
      idGrid: 'app-grid_a18',
      category: AppCategory.Other,
      label: 'Camera',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a19',
      idGrid: 'app-grid_a19',
      category: AppCategory.Other,
      label: 'Test 4 4 4 4 4 4 4',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a20',
      idGrid: 'app-grid_a20',
      category: AppCategory.Other,
      label: 'Test 5',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a21',
      idGrid: 'app-grid_a21',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a22',
      idGrid: 'app-grid_a22',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a23',
      idGrid: 'app-grid_a23',
      category: AppCategory.Other,
      label: 'Camera',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
  ],

  [
    {
      id: 'a24',
      idGrid: 'app-grid_a24',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a25',
      idGrid: 'app-grid_a25',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a26',
      idGrid: 'app-grid_a26',
      category: AppCategory.Other,
      label: 'Camera',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a27',
      idGrid: 'app-grid_a27',
      category: AppCategory.Other,
      label: 'Test 4 4 4 4 4 4 4',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a28',
      idGrid: 'app-grid_a28',
      category: AppCategory.Other,
      label: 'Test 5',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a29',
      idGrid: 'app-grid_a29',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a30',
      idGrid: 'app-grid_a29',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a31',
      idGrid: 'app-grid_a31',
      category: AppCategory.Other,
      label: 'Camera',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a32',
      idGrid: 'app-grid_a32',
      category: AppCategory.Other,
      label: 'Test 4 4 4 4 4 4 4',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a33',
      idGrid: 'app-grid_a33',
      category: AppCategory.Other,
      label: 'Test 5',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a34',
      idGrid: 'app-grid_a34',
      category: AppCategory.Other,
      label: 'Calendar',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
    {
      id: 'a35',
      idGrid: 'app-grid_a35',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
  ],

  [
    {
      id: 'a36',
      idGrid: 'app-grid_a36',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
  ],

  [
    {
      id: 'a37',
      idGrid: 'app-grid_a37',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
  ],

  [
    {
      id: 'a38',
      idGrid: 'app-grid_a38',
      category: AppCategory.Other,
      label: 'Photos',
      icon: AppVoidIconComponent,
      app: AppVoidComponent,
    },
  ],
];

const defaultApps: ApplicationInstalled[] = [
  {
    id: 'app-settings',
    idGrid: 'app-grid_settings',
    category: AppCategory.Other,
    label: 'Settings',
    icon: AppSettingsIconComponent,
    app: AppSettingsComponent,
  },
  {
    id: 'app-clock',
    idGrid: 'app-grid_clock',
    category: AppCategory.Other,
    label: 'Clock',
    icon: AppClockIconComponent,
    app: AppClockComponent,
  },
  {
    id: 'app-void',
    idGrid: 'app-grid_void',
    category: AppCategory.Other,
    label: 'Photos',
    icon: AppVoidIconComponent,
    app: AppVoidComponent,
  },
];


@Injectable()
export class IosInstalledAppsService {

  readonly apps = signal<ApplicationInstalled[]>([
    ...defaultApps,
  ]);
  readonly appsGrid = signal<ApplicationInstalled[][]>(appsGrid);

}
